header = ("---------------------------------------------\n"
          "larrabyte/boggler: a text-adventure RPG game.\n"
          "---------------------------------------------")

initial = ("  ()-()\n"
           ".-(___)-. freelsd development kernel\n"
           " _<   >_  kermit says guten tag\n"
           " \\/   \\/\n\n")

bootstrap = ("kernel: kprintf initialized\n"
             "kernel: initialize_screen: b=9DF438000, w=00000A00, h=00000640, r=00002800, d=00000000\n"
             "kernel: pe_arm_init_interrupts: args: <private>\n"
             "kernel: pe_arm_map_interrupt_controller: soc_phys:  0x200000000\n"
             "kernel: pe_arm_map_interrupt_controller: found interrupt-controller\n"
             "kernel: pe_arm_map_interrupt_controller: gPicBase: 0x<private>\n"
             "kernel: pe_arm_map_interrupt_controller: found timer\n"
             "kernel: pe_arm_map_interrupt_controller: gTimerBase: 0x<private>\n"
             "kernel: FreeLSD Kernel Version 15.2.00: Sun Mar 14 14:25:51 AEDT 2069; root:lsd/RELEASE_ARM256\n"
             "kernel: pmap_startup() init/release time: 7446 microsec\n"
             "kernel: pmap_startup() delayed init/release of 0 pages\n"
             "kernel: vm_page_bootstrap: 472513 free pages, 10132 wired pages, (up to 0 of which are delayed free)\n"
             "kernel: \"vm_compressor_mode\" is 4\n"
             "kernel: IOKit IOMD setownership ENABLED\n"
             "kernel: oslog_init completed, 16 chunks, 8 io pages\n"
             "kernel: Telemetry: Sampling all tasks once per 1 second\n"
             "kernel: Scheduler: Default of edge\n"
             "kernel: Setting scheduler priority decay band limit 18\n"
             "kernel: standard timeslicing quantum is 10000 us\n"
             "kernel: standard background quantum is 2500 us\n"
             "kernel: WQ[wql_init]: init linktable with max:262144 elements (8388608 bytes)\n"
             "kernel: WQ[wqp_init]: init prepost table with max:262144 elements (8388608 bytes)\n"
             "kernel: mig_table_max_displ = 53 mach_kobj_count = 365\n"
             "kernel: ATM subsystem is initialized\n"
             "kernel: BANK subsystem is initialized\n"
             "kernel: IPC_PTHREAD_PRIORITY subsystem is initialized\n"
             "kernel: kdp_core zlib memory 0x8000\n"
             "kernel: Registered coredump handler for kernel\n"
             "kernel: Serial requested, consistent debug disabled or debug boot arg not present, configuring debugging over serial\n"
             "kernel: Initializing serial KDP\n"
             "kernel: mlgBoot version: mlgBoot-6723.81.1\n"
             "kernel: KextLog: Collection UUID matches with loaded KCs.\n"
             "kernel: (corecrypto) corecrypto_kext_start called\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [151929727] fipspost_post:157: [FIPSPOST][Module-ID] FreeLSD corecrypto Module v11.1 [FreeLSD ARM, Kernel, Software]\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [151930167] fipspost_post:168: PASSED: (0 ms) - fipspost_post_hmac\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [151935025] fipspost_post:169: PASSED: (0 ms) - fipspost_post_integrity\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [151935288] fipspost_post:175: PASSED: (0 ms) - fipspost_post_indicator\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [151935361] fipspost_post:176: PASSED: (0 ms) - fipspost_post_aes_ecb\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [151935432] fipspost_post:177: PASSED: (0 ms) - fipspost_post_aes_cbc\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152041790] fipspost_post:178: PASSED: (4 ms) - fipspost_post_rsa_sig\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152249877] fipspost_post:179: PASSED: (8 ms) - fipspost_post_ecdsa\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152256437] fipspost_post:180: PASSED: (0 ms) - fipspost_post_ecdh\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152256542] fipspost_post:181: PASSED: (0 ms) - fipspost_post_aes_ccm\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152256683] fipspost_post:182: PASSED: (0 ms) - fipspost_post_aes_cmac\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152435695] fipspost_post:184: PASSED: (7 ms) - fipspost_post_pbkdf\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152435870] fipspost_post:185: PASSED: (0 ms) - fipspost_post_kdf_ctr\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152435948] fipspost_post:186: PASSED: (0 ms) - fipspost_post_aes_gcm\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152436017] fipspost_post:187: PASSED: (0 ms) - fipspost_post_aes_xts\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152437750] fipspost_post:188: PASSED: (0 ms) - fipspost_post_tdes_cbc\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152437980] fipspost_post:189: PASSED: (0 ms) - fipspost_post_drbg_ctr\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152438556] fipspost_post:190: PASSED: (0 ms) - fipspost_post_drbg_hmac\n"
             "kernel: (corecrypto) FIPSPOST_KEXT [152438598] fipspost_post:213: all tests PASSED (21 ms)\n"
             "kernel: Matching service count = 0\n"
             "kernel: Matching service count = 0\n"
             "kernel: Matching service count = 0\n"
             "kernel: Matching service count = 0\n"
             "kernel: Matching service count = 0\n"
             "kernel: Matching service count = 0\n"
             "kernel: (FreeLSDImage4) FreeLSD Image4 Validator Version 2.3.00: Sun Mar 14 14:25:51 AEDT 2069; root:FreeLSDImage4-106.40.12~3668/FreeLSDImage4/RELEASE_ARM256X\n"
             "kernel: calling mpo_policy_init for FMFI\n"
             "kernel: Security policy loaded: FreeLSD Mobile File Integrity (FMFI)\n"
             "kernel: calling mpo_policy_init for Sandbox\n"
             "kernel: Security policy loaded: Seatbelt sandbox policy (Sandbox)\n"
             "kernel: calling mpo_policy_init for Quarantine\n"
             "kernel: Security policy loaded: Quarantine policy (Quarantine)\n"
             "kernel: 2 external trust cache modules available.\n"
             "kernel: external trust cache module 0 with 16133 entries\n"
             "kernel: external trust cache module 1 with 1003 entries\n"
             "kernel: keepsyms boot arg specified; keeping linkedit segment for symbols.\n"
             "kernel: (InvalidateHmac) Beginning SIO HMAC invalidation...\n"
             "kernel: (InvalidateHmac) Finished SIO HMAC invalidation.\n"
             "kernel: PMRD: PMTraceWorker 0x93d35f8d6ddc148f\n"
             "kernel: PMRD: changePowerStateWithTagToPriv(ON_STATE, 10001)\n"
             "kernel: (IOGraphicsFamily) IOG flags 0x3 (0x51)\n"
             "kernel: (AUC) AUC:[0xfffffe233669c500]::init(0xfffffe166d15d7e8)\n"
             "kernel: PMRD: power event 7 args 0x93d35f8d6dcfa5af 0x0\n"
             "kernel: Copyright (c) 1982, 1986, 1989, 1991, 1993, 2069\n"
             "        Property of r/wallstreetbets. All rights reserved.\n\n")

final1 = ("kernel: AIC setup complete, interrupts ready\n")
final2 = ("kernel: Reticulating splines\n")
final3 = ("kernel: Boot complete\a")
